// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://perztjvjswgfwaevvrgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcnp0anZqc3dnZndhZXZ2cmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTc2MzIsImV4cCI6MjA2ODM5MzYzMn0.6zoik6wjmXL0XcdZ06Wg1NixzK4gZXROMV4kDvcS0kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});